Product and subclasses
develhope/Java23-Team1-Warehouse pull request #2
Opened 2024-02-28 18:29 UTC by Sijia18

2024-02-28 18:30 UTC, gabrielD4 requested changes

2024-02-28 18:30 UTC, gabrielD4 commented on src/Notebook.java
> +    public Notebook(String device, String brand, String model, String description, float display, float storage,
Mancano i get e set

2024-02-29 14:32 UTC, gabrielD4 requested changes

2024-02-29 14:32 UTC, gabrielD4 commented on src/products/Notebook.java
> +package products;
Ci sono da fare le modifiche che ti dicevo su discord

2024-02-29 18:15 UTC, gabrielD4 requested changes

2024-02-29 18:15 UTC, gabrielD4 commented on src/products/Enum.java
> +enum products {
La P deve essere maiuscola. Inoltre forse lo chiamerei Devices per chiarezza.

2024-02-29 18:15 UTC, gabrielD4 commented on src/products/Product.java
> +    private String device;
però dell'enum non hai dichiarato la variabile privata
devi farlo mettendo anche i rispettivi get e set
al posto dell'attrivuto String device devi mettere l'attributo private Devices deviceType.

2024-03-01 09:31 UTC, gabrielD4 approved these changes

2024-03-01 09:31 UTC, merged

2024-03-01 09:31 UTC, hatefulTtamer approved these changes