deleted class ResearchMethod and class Test, moved method search into Warehouse
develhope/Java23-Team1-Warehouse pull request #31
Opened 2024-03-20 09:48 UTC by hatefulTtamer

2024-03-20 12:34 UTC, gabrielD4 requested changes

2024-03-20 12:34 UTC, gabrielD4 commented on src/Warehouse.java
>      public List<Product> filterBySaleRange(Integer minPrice, Integer maxPrice) {
Anche questi filtri vanno eliminati

2024-03-21 11:23 UTC, gabrielD4 approved these changes

2024-03-21 12:02 UTC, closed without merging

2024-03-21 12:03 UTC, hatefulTtamer commented
Created a new branch and resolved various conflicts with other merges.