Test package
develhope/Java23-Team1-Warehouse pull request #40
Opened 2024-03-25 19:13 UTC by fab-bob

ho aggiunto il package dei test con tutte le classi tranne l'interfaccia dei filtri. Ho aggiunto anche dei prototipi di test che ovviamente vanno implementati.

2024-03-26 09:06 UTC, gabrielD4 requested changes

2024-03-26 09:06 UTC, gabrielD4 commented on test/CartTest.java
> +    @org.junit.jupiter.api.Test
Cambia la notazione in @Test

2024-03-26 14:46 UTC, gabrielD4 requested changes

2024-03-26 14:46 UTC, gabrielD4 commented on src/Warehouse.java
> +    public double calculateAveragePurchasePriceByDeviceType(Devices deviceType) throws InvalidSearchFilterException {
Attento questo metodo è finito in questo commit. Inoltre è la versione errata ancora. Probabilmente hai staccato un branch non dal main ma dal branch in cui già stavi lavorando.

2024-03-27 12:51 UTC, SIlvioVutea approved these changes
metto l'approve così da poter fare il merge una volta portato il branch in pari col main .

2024-03-27 15:15 UTC, gabrielD4 approved these changes
Noice

2024-03-27 15:15 UTC, merged