create some test
develhope/Java23-Team1-Warehouse pull request #64
Opened 2024-04-04 18:49 UTC by Sijia18

2024-04-04 20:27 UTC, SIlvioVutea requested changes

2024-04-04 20:27 UTC, SIlvioVutea commented on src/test/java/warehouse/CartTest.java
> +    void addToCartById_cartValidSize() throws InvalidIdException {
sarebbe meglio che verificassi se l'oggetto aggiunto a cart è l'oggetto che volevi invece di verificare l'aumento della size del carrello

2024-04-04 20:27 UTC, SIlvioVutea commented on src/test/java/warehouse/CartTest.java
> +    void addToCartById_cartIsEmpty() {
se il carrello è vuoto o meno è irrilevante ai fini di questo metodo

2024-04-04 20:27 UTC, SIlvioVutea commented on src/test/java/warehouse/CartTest.java
> +    void addToCartById_warehouseIsEmpty() {
testerei l'InvalidIdExeption che è strettamente legata al tuo metodo piuttosto che testare un semplice isEmpty totalmente sconnesso dal tuo metodo .è quella l'exception che ti lancia anche nel caso di magazzino vuoto perchè non troverà un id valido

2024-04-05 11:04 UTC, closed without merging

2024-04-05 11:04 UTC, Sijia18 commented
creo una nuova, mi clono il progetto