ho rinominato i test in modo più intuitivo, a scanso di equivoci e aggiunto un if al metodo in cart
develhope/Java23-Team1-Warehouse pull request #69
Opened 2024-04-05 12:55 UTC by Sijia18

2024-04-05 13:44 UTC, SIlvioVutea requested changes

2024-04-05 13:44 UTC, SIlvioVutea commented on src/test/java/warehouse/CartTest.java
> +    void addToCartById_checkInvalidIdExceptionWhenWarehouseIsEmpty() throws InvalidIdException, EmptyWarehouseException {
come ti dicevo puoi usare questa exception per testare anche il caso in cui l'id che stai cercando di aggiungere col metodo sia già presente nel cart. Puoi anche partire dal test per poi implementare il relativo controllo nel metodo che dovrebbe appunto lanciare questa eccezione .

2024-04-09 08:15 UTC, SIlvioVutea requested changes

2024-04-09 08:15 UTC, SIlvioVutea commented on src/main/java/warehouse/Cart.java
> +                throw new InvalidIdException("You have already add this product!");
tornerei il messaggio "this id already exist in Cart" nell'exceptionn e come dicevamo in call implementerei questo controllo in un metodo ceh torna un bollano che chiami qua all'inizio

2024-04-09 13:54 UTC, gabrielD4 requested changes

2024-04-09 13:54 UTC, gabrielD4 commented on src/main/java/warehouse/Cart.java
> +    public void addToCartBySameId(FilterById filterById) throws InvalidIdException {
il metodo si che lo hai estrapolato, ma poi devi richiamarlo nel metodo principale. Inoltre il nome del metodo è sbagliato rispetto alla sua funzione.

2024-04-10 08:13 UTC, gabrielD4 approved these changes

2024-04-10 09:07 UTC, SIlvioVutea approved these changes

2024-04-10 15:01 UTC, merged