Test search
develhope/Java23-Team1-Warehouse pull request #71
Opened 2024-04-09 13:18 UTC by gabrielD4

2024-04-09 13:59 UTC, hatefulTtamer requested changes
Riga 162

2024-04-09 13:59 UTC, hatefulTtamer commented on src/test/java/warehouse/WarehouseTest.java
> +    void testSearch_wrongPurchasePriceRange_minPriceOverMaxPrice() {
Questo metodo dovrebbe specificare che throwa un exception.

2024-04-09 14:06 UTC, hatefulTtamer approved these changes

2024-04-09 14:09 UTC, hatefulTtamer approved these changes

2024-04-10 08:16 UTC, Sijia18 approved these changes

2024-04-10 08:17 UTC, merged