ProductTest (senza builder)
develhope/Java23-Team1-Warehouse pull request #83
Opened 2024-04-12 12:13 UTC by Sijia18

Ho creato il package products per i tests della classe productTest 
ho testato i due metodi che ho creato, in alternatva al builder 
e che controllano al medesimo modo le condizioni che volevamo

2024-04-12 13:16 UTC, SIlvioVutea requested changes

2024-04-12 13:16 UTC, SIlvioVutea commented on src/main/java/products/Product.java
> +            throw new IndexOutOfBoundsException("You can only use positive values.");
trova una exception più pertinente di questa

2024-04-12 13:17 UTC, hatefulTtamer requested changes

2024-04-12 13:17 UTC, hatefulTtamer commented on src/main/java/products/Product.java
> +            throw new IndexOutOfBoundsException("You can only use positive values.");
IndexOutOfBound non è la giusta eccezione da utilizzare in questo caso

2024-04-12 13:17 UTC, hatefulTtamer commented on src/main/java/products/Product.java
> +        }
Questi due metodi potrebbero benissimo convergere in uno unico

2024-04-12 13:24 UTC, SIlvioVutea commented
non capisco perchè applichi questi controlli con due metodi che poi richiami direttamente sui prodotti invece di implementarli nel costruttore e nei setter, magari mi sbaglio e mi sfugge qualcosa ma credo questi controlli dovrebbero essere funzionali prima della creazione dei prodotti .

2024-04-15 08:36 UTC, SIlvioVutea approved these changes

2024-04-15 09:32 UTC, gabrielD4 approved these changes

2024-04-15 09:32 UTC, gabrielD4 commented on src/main/java/products/Product.java
> +    public void validateValues(DeviceType deviceType, String brand, String model, String description, float display, float storage, float purchasePrice, float salePrice, int id) throws IllegalArgumen
Come avevamo detto in chiamata e come abbiamo sempre fatto con Lorenzo, questi controlli vanno messi nel costruttore, così nulla ti vieta di creare prodotti non validi

2024-04-15 09:43 UTC, hatefulTtamer approved these changes

2024-04-15 09:43 UTC, hatefulTtamer commented on src/test/java/products/ProductTest.java
> +    public void product_withOutBrand() {
Anche se è solo il nome di un test, cerca di fare attenzione alla scrittura in quanto è "without", non sono due parole

2024-04-15 09:44 UTC, merged