Check string
develhope/Java23-Team1-Warehouse pull request #85
Opened 2024-04-13 17:53 UTC by hatefulTtamer

2024-04-14 13:53 UTC, gabrielD4 requested changes

2024-04-14 13:53 UTC, gabrielD4 commented on src/main/java/controller/Controller.java
> +    public static String trimWhiteSpace(String input) {
Non nego funzioni, ma esiste il metodo .trim() per le stringhe che fa questa cosa.

2024-04-14 13:53 UTC, gabrielD4 commented on src/main/java/controller/Controller.java
> +    public static boolean validateString(String input) {
Questo metodo deve lavorare con lo scanner, inoltre non deve ritornare un boolean, ma deve ritornare la stringa di input dall'utente. Te devi controllare la strigna da input dall'utente con lo scanner, conrollare che rispetti le limitazioni, tagliarla dagli spazi e ritornarla.

2024-04-14 14:36 UTC, hatefulTtamer commented on src/main/java/controller/Controller.java
> +    public static String trimWhiteSpace(String input) {
Il metodo trim() non funzionava in quanto rimuove gli spazi solo all'inizio e alla fine della String

2024-04-14 14:38 UTC, hatefulTtamer commented on src/main/java/controller/Controller.java
> +    public static boolean validateString(String input) {
Allora modifico il metodo in quanto io l'avevo creato come boolean in quanto validate (yes or not)

2024-04-15 09:30 UTC, gabrielD4 requested changes

2024-04-15 09:30 UTC, gabrielD4 commented on src/main/java/controller/Controller.java
> +    public static String trimWhiteSpace(String input) {
eh si vedevo ora che l'unica è farla a mano allora. Allora chiama il metodo removeWhiteSpaceFrom. Perchè trim non è ciò che stai facendo. Inserire From alla fine invece è una convenzione per queste cose, fai capire che stai rimuovendo dal parametro che gli stai passando.

2024-04-18 13:25 UTC, gabrielD4 approved these changes

2024-04-18 13:57 UTC, merged